### Стенд для локальной разработки
version: '3.9'
name: meteoStation
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_MAX_CONNECTIONS: 1000
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6135:5432"

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - homebridge_data:/homebridge
    ports:
      - "8581:8581"
      - "51828:51828"
    environment:
      - TZ=Europe/Moscow
      - ENABLE_AVAHI=0

volumes:
  homebridge_data:
